/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TaskControl.paneles;

import TaskControl.modelos.Tableros;
import javax.swing.JOptionPane;
import taskcontrol.interfaces.DAOTablero;
import taskcontrol.paneles.Tablero;
import taskcontrol.vistas.DAOTableroImpl;
import static taskcontrol.vistas.TCDashboard.mostrarPanel;

/**
 *
 * @author jonat
 */
public class AgregarTarea extends javax.swing.JPanel {

    /**
     * Creates new form AcercaDe
     */
    public AgregarTarea() {
        initComponents();
    }

    private void crearTarea() {
        String nombreTareaCampo = txtNombreTarea.getText();
        String descripcionTareaCampo = taDescripcionTarea.getText();

        if (nombreTareaCampo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes colocar el nombre de la tarea.");
            txtNombreTarea.requestFocus();
            return;
        }

        Tableros tarea = new Tableros();
        tarea.setLista_tareas(nombreTareaCampo);
        tarea.setDescripcion_tarea(descripcionTareaCampo);

        try {
            DAOTablero dao = new DAOTableroImpl();
            dao.agregarTarea(tarea);

            JOptionPane.showMessageDialog(null, "Tarea agregada satisfactoriamente.");

            txtNombreTarea.setText("");
            taDescripcionTarea.setText("");

            mostrarPanel(new Tablero());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: No se pudo agregar la tarea.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarTarea = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcionTarea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(32, 36, 47));

        btnAgregarTarea.setBackground(new java.awt.Color(63, 128, 190));
        btnAgregarTarea.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAgregarTarea.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarTarea.setText("Agregar tarea");
        btnAgregarTarea.setBorder(null);
        btnAgregarTarea.setBorderPainted(false);
        btnAgregarTarea.setMargin(new java.awt.Insets(2, 20, 3, 20));
        btnAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTareaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de tarea:");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripción de tarea:");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Panel de agregar tareas:");

        txtNombreTarea.setBackground(new java.awt.Color(59, 67, 87));
        txtNombreTarea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreTarea.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreTarea.setMargin(new java.awt.Insets(4, 10, 4, 10));

        taDescripcionTarea.setBackground(new java.awt.Color(59, 67, 87));
        taDescripcionTarea.setColumns(20);
        taDescripcionTarea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        taDescripcionTarea.setForeground(new java.awt.Color(255, 255, 255));
        taDescripcionTarea.setLineWrap(true);
        taDescripcionTarea.setRows(1);
        taDescripcionTarea.setBorder(null);
        taDescripcionTarea.setMargin(new java.awt.Insets(4, 10, 4, 10));
        jScrollPane1.setViewportView(taDescripcionTarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)))
                .addGap(108, 329, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
        crearTarea();
    }//GEN-LAST:event_btnAgregarTareaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDescripcionTarea;
    private javax.swing.JTextField txtNombreTarea;
    // End of variables declaration//GEN-END:variables
}
