/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TaskControl.paneles;

import TaskControl.modelos.Tableros;
import taskcontrol.paneles.Tablero;
import static taskcontrol.vistas.TCDashboard.mostrarPanel;

/**
 * Clase que representa el panel de edición de tareas
 */
public class MostrarTareaNomDescp extends javax.swing.JPanel {

    private String nombreTarea;
    private String descripcionTarea;
    private int idTarea1;

    /**
     * Creates new form EdicionTarea
     */
    public MostrarTareaNomDescp() {
        initComponents();
    }

    /**
     * Método para establecer el nombre de la tarea en el campo correspondiente
     *
     * @param nombre El nombre de la tarea
     */
    public void setNombreTarea(String nombre) {
        nombreTarea = nombre;
        lbNombreTarea.setText(nombreTarea);
    }

    public void setIdTarea(int idTarea) {
        idTarea1 = idTarea;
    }

    /**
     * Método para establecer la descripción de la tarea en el campo
     * correspondiente
     *
     * @param descripcion La descripción de la tarea
     */
    public void setDescripcionTarea(String descripcion) {
        descripcionTarea = descripcion;
        taDescripcionTarea.setText(descripcionTarea);
    }

    private void edicionTarea() {
        String nombreTarea = lbNombreTarea.getText();
        String descripcionTarea = taDescripcionTarea.getText();

        Tableros tarea = new Tableros();
        tarea.setLista_tareas(nombreTarea);
        tarea.setDescripcion_tarea(descripcionTarea);
        tarea.setId_tarea(idTarea1);

        mostrarPanel(new Tablero());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcionTarea = new javax.swing.JTextArea();
        lbNombreTarea = new javax.swing.JLabel();

        setBackground(new java.awt.Color(32, 36, 47));

        btnEditar.setBackground(new java.awt.Color(63, 128, 190));
        btnEditar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Volver");
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setMargin(new java.awt.Insets(2, 20, 3, 20));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de tarea:");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripción de tarea:");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Panel de visulización tareas:");

        taDescripcionTarea.setEditable(false);
        taDescripcionTarea.setBackground(new java.awt.Color(32, 36, 47));
        taDescripcionTarea.setColumns(20);
        taDescripcionTarea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        taDescripcionTarea.setForeground(new java.awt.Color(255, 255, 255));
        taDescripcionTarea.setLineWrap(true);
        taDescripcionTarea.setRows(1);
        taDescripcionTarea.setText("descripcion_tarea");
        taDescripcionTarea.setMargin(new java.awt.Insets(4, 10, 4, 10));
        jScrollPane1.setViewportView(taDescripcionTarea);

        lbNombreTarea.setBackground(new java.awt.Color(57, 65, 84));
        lbNombreTarea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbNombreTarea.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreTarea.setText("lista_tarea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        edicionTarea();
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNombreTarea;
    private javax.swing.JTextArea taDescripcionTarea;
    // End of variables declaration//GEN-END:variables
}
