/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taskcontrol.vistas;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author jonat
 */
public class TCPrincipal extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form interfazPrincipal
     */
    public TCPrincipal() {
        initComponents();
        SetImageLabel(lbFondo, "src/TaskControl/imagenes/imagenFondo.png");
        SetImageLabel(lbTaskControl, "src/TaskControl/imagenes/taskcontrol.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContenedorPadre = new javax.swing.JPanel();
        barraFuncional = new javax.swing.JPanel();
        equisCierrePanel = new javax.swing.JPanel();
        lbEquis = new javax.swing.JLabel();
        pContenedorCont = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pInicioSesion = new javax.swing.JPanel();
        lbInicioSesionImg = new javax.swing.JLabel();
        lbYaTienesUnaCuenta = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pCreaUna = new javax.swing.JPanel();
        lbRegistroImg = new javax.swing.JLabel();
        lbNoTienesCuenta = new javax.swing.JLabel();
        btnCreaUna = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTaskControl = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 607));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pContenedorPadre.setPreferredSize(new java.awt.Dimension(720, 607));
        pContenedorPadre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraFuncional.setBackground(new java.awt.Color(24, 36, 68));
        barraFuncional.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraFuncional.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraFuncionalMouseDragged(evt);
            }
        });
        barraFuncional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraFuncionalMousePressed(evt);
            }
        });
        barraFuncional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equisCierrePanel.setBackground(new java.awt.Color(172, 51, 51));
        equisCierrePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        equisCierrePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                equisCierrePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                equisCierrePanelMouseExited(evt);
            }
        });

        lbEquis.setBackground(new java.awt.Color(172, 51, 51));
        lbEquis.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbEquis.setForeground(new java.awt.Color(255, 255, 255));
        lbEquis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEquis.setText("X");
        lbEquis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbEquis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbEquisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout equisCierrePanelLayout = new javax.swing.GroupLayout(equisCierrePanel);
        equisCierrePanel.setLayout(equisCierrePanelLayout);
        equisCierrePanelLayout.setHorizontalGroup(
            equisCierrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbEquis, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        equisCierrePanelLayout.setVerticalGroup(
            equisCierrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbEquis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        barraFuncional.add(equisCierrePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 30));

        pContenedorPadre.add(barraFuncional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

        pContenedorCont.setBackground(new java.awt.Color(46, 50, 63));
        pContenedorCont.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pContenedorCont.setEnabled(false);
        pContenedorCont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Task Control");
        pContenedorCont.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 160, -1));

        pInicioSesion.setBackground(new java.awt.Color(46, 50, 63));
        pInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pInicioSesion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        pInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pInicioSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pInicioSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pInicioSesionMouseExited(evt);
            }
        });
        pInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbInicioSesionImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInicioSesionImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaskControl/imagenes/usuarioImg.png"))); // NOI18N
        lbInicioSesionImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pInicioSesion.add(lbInicioSesionImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        lbYaTienesUnaCuenta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbYaTienesUnaCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lbYaTienesUnaCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbYaTienesUnaCuenta.setText("¿Ya tienes cuenta?");
        lbYaTienesUnaCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pInicioSesion.add(lbYaTienesUnaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, -1));

        btnInicioSesion.setBackground(new java.awt.Color(92, 147, 200));
        btnInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(63, 128, 190));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicia sesión");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInicioSesion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 170, 30));

        pInicioSesion.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 170, 40));

        pContenedorCont.add(pInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        pCreaUna.setBackground(new java.awt.Color(46, 50, 63));
        pCreaUna.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pCreaUna.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        pCreaUna.setVerifyInputWhenFocusTarget(false);
        pCreaUna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCreaUnaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCreaUnaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCreaUnaMouseExited(evt);
            }
        });
        pCreaUna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegistroImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegistroImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaskControl/imagenes/usuarioRegImg.png"))); // NOI18N
        lbRegistroImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pCreaUna.add(lbRegistroImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        lbNoTienesCuenta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbNoTienesCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lbNoTienesCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNoTienesCuenta.setText("¿No tienes cuenta?");
        lbNoTienesCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pCreaUna.add(lbNoTienesCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, -1));

        btnCreaUna.setBackground(new java.awt.Color(92, 147, 200));
        btnCreaUna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(63, 128, 190));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crea una");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreaUna.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 170, 30));

        pCreaUna.add(btnCreaUna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 40));

        pContenedorCont.add(pCreaUna, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pContenedorCont.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, 10));
        pContenedorCont.add(lbTaskControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 80, 80));

        pContenedorPadre.add(pContenedorCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 600, 420));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaskControl/imagenes/imagenFondo.png"))); // NOI18N
        pContenedorPadre.add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 730, 620));

        getContentPane().add(pContenedorPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 607));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbEquisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEquisMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbEquisMouseClicked

    private void equisCierrePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisCierrePanelMouseEntered
        // TODO add your handling code here:
        equisCierrePanel.setBackground(new Color(190, 51, 51));
    }//GEN-LAST:event_equisCierrePanelMouseEntered

    private void equisCierrePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equisCierrePanelMouseExited
        // TODO add your handling code here:
        equisCierrePanel.setBackground(new Color(172, 51, 51));
    }//GEN-LAST:event_equisCierrePanelMouseExited

    private void barraFuncionalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraFuncionalMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraFuncionalMouseDragged

    private void barraFuncionalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraFuncionalMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraFuncionalMousePressed

    private void pInicioSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInicioSesionMouseEntered
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        pInicioSesion.setBackground(new Color(56, 59, 73));
        btnInicioSesion.setBackground(new Color(92, 147, 200));
    }//GEN-LAST:event_pInicioSesionMouseEntered

    private void pCreaUnaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCreaUnaMouseEntered
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        pCreaUna.setBackground(new Color(56, 59, 73));
        btnCreaUna.setBackground(new Color(92, 147, 200));
    }//GEN-LAST:event_pCreaUnaMouseEntered

    private void pInicioSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInicioSesionMouseExited
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pInicioSesion.setBackground(new Color(46, 50, 63));
        btnInicioSesion.setBackground(new Color(63, 128, 190));
    }//GEN-LAST:event_pInicioSesionMouseExited

    private void pCreaUnaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCreaUnaMouseExited
        // TODO add your handling code here:
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pCreaUna.setBackground(new Color(46, 50, 63));
        btnCreaUna.setBackground(new Color(63, 128, 190));
    }//GEN-LAST:event_pCreaUnaMouseExited

    private void pInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pInicioSesionMouseClicked
        // TODO add your handling code here:
        System.out.println("Boton funcionando");
        TCInicioSesion frmInicioSesion = new TCInicioSesion();
        frmInicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pInicioSesionMouseClicked

    private void pCreaUnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCreaUnaMouseClicked
        // TODO add your handling code here:
        System.out.println("Boton funcionando");
        TCRegistroUsuario frmRegistroUsuario = new TCRegistroUsuario();
        frmRegistroUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pCreaUnaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        UIManager.put("Button.arc", 20);
//        UIManager.put("Component.arc", 999);
//        UIManager.put("ProgressBar.arc", 999);
//        UIManager.put("TextComponent.arc", 999);
        UIManager.put("TabbedPane.selectedBackground", Color.white);
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCPrincipal().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_AREA_AVERAGING));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraFuncional;
    private javax.swing.JPanel btnCreaUna;
    private javax.swing.JPanel btnInicioSesion;
    private javax.swing.JPanel equisCierrePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbEquis;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbInicioSesionImg;
    private javax.swing.JLabel lbNoTienesCuenta;
    private javax.swing.JLabel lbRegistroImg;
    private javax.swing.JLabel lbTaskControl;
    private javax.swing.JLabel lbYaTienesUnaCuenta;
    private javax.swing.JPanel pContenedorCont;
    private javax.swing.JPanel pContenedorPadre;
    private javax.swing.JPanel pCreaUna;
    private javax.swing.JPanel pInicioSesion;
    // End of variables declaration//GEN-END:variables
}
